drpcorg/dshackle

src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/WsConnection.kt

Cherry-picked commits fixing WS connection

Fix reconnect dos ws

---

.gitmodules
gradle/libs.versions.toml
settings.gradle
src/main/kotlin/io/emeraldpay/dshackle/proxy/WebsocketHandler.kt
src/main/kotlin/io/emeraldpay/dshackle/rpc/NativeSubscribe.kt
src/main/kotlin/io/emeraldpay/dshackle/rpc/TrackERC20Address.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumLikeMultistream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumMultistream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumSubscribe.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/subscribe/ConnectBlockUpdates.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/subscribe/ConnectLogs.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/subscribe/ConnectNewHeads.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum_pos/EthereumPosMultiStream.kt
src/test/groovy/io/emeraldpay/dshackle/proxy/WebsocketHandlerSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/rpc/NativeSubscribeSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/rpc/TrackERC20AddressSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/test/MultistreamHolderMock.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/subscribe/ConnectBlockUpdatesSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/subscribe/ConnectNewHeadsSpec.groovy

Revert "Native subscribe filter"

---

.gitmodules
gradle/libs.versions.toml
settings.gradle
src/main/kotlin/io/emeraldpay/dshackle/proxy/WebsocketHandler.kt
src/main/kotlin/io/emeraldpay/dshackle/rpc/NativeSubscribe.kt
src/main/kotlin/io/emeraldpay/dshackle/rpc/TrackERC20Address.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumLikeMultistream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumMultistream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumSubscribe.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/subscribe/ConnectBlockUpdates.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/subscribe/ConnectLogs.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/subscribe/ConnectNewHeads.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum_pos/EthereumPosMultiStream.kt
src/test/groovy/io/emeraldpay/dshackle/proxy/WebsocketHandlerSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/rpc/NativeSubscribeSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/rpc/TrackERC20AddressSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/test/MultistreamHolderMock.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/subscribe/ConnectBlockUpdatesSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/subscribe/ConnectNewHeadsSpec.groovy

Revert "Revert "Native subscribe filter""

---

build.gradle
gradle/libs.versions.toml
src/main/kotlin/io/emeraldpay/dshackle/Config.kt
src/test/kotlin/io/emeraldpay/dshackle/IntegrationTest.kt
src/test/resources/integration/dshackle.yaml

First iteration of spring integration tests with API calls

Integration tests with ganache and SpringBootTest

---

src/main/kotlin/io/emeraldpay/dshackle/GrpcServer.kt

Added custom executor for grpc server with fixed 20 threads. Default thread pool is unbounded :(

Added custom executor for grpc

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/WsConnection.kt
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/WsConnectionSpec.groovy

problem: timeout on unit tests

problem: timeout on unit tests

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/WsConnection.kt
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/WsConnectionSpec.groovy

Revert "problem: timeout on unit tests"

---

src/main/kotlin/io/emeraldpay/dshackle/commons/DynamicMergeFlux.kt
src/main/kotlin/io/emeraldpay/dshackle/config/context/MultistreamsConfig.kt
src/main/kotlin/io/emeraldpay/dshackle/config/context/SchedulersConfig.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/DynamicMergedHead.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumMultistream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum_pos/EthereumPosMultiStream.kt
src/test/groovy/io/emeraldpay/dshackle/test/MultistreamHolderMock.groovy
src/test/groovy/io/emeraldpay/dshackle/test/TestingCommons.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/MultistreamSpec.groovy

- add injection of schedulers for dynamic heads
- more logging
- replace onBackpressureBuffer to directBestEffort multicast sink

Small improvements after dynamic head introduction

---

src/main/kotlin/io/emeraldpay/dshackle/GrpcServer.kt
src/main/kotlin/io/emeraldpay/dshackle/config/context/SchedulersConfig.kt
src/main/kotlin/io/emeraldpay/dshackle/startup/ConfiguredUpstreams.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/Multistream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/grpc/EthereumPosGrpcUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/grpc/GrpcUpstreams.kt
src/test/groovy/io/emeraldpay/dshackle/startup/ConfiguredUpstreamsSpec.groovy

- added fixed channel executor thread pool
- lag observer should be created only in case there are more than 1 upstreams exists
- fixed small typos in thread pools names

Fix extra cpu usage 2

---

src/main/kotlin/io/emeraldpay/dshackle/rpc/SubscribeStatus.kt
src/main/kotlin/io/emeraldpay/dshackle/startup/ConfiguredUpstreams.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/DefaultUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/DynamicMergedHead.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumMultistream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum_pos/EthereumPosMultiStream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/grpc/BitcoinGrpcUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/grpc/EthereumPosGrpcUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/grpc/GrpcUpstreams.kt
src/test/groovy/io/emeraldpay/dshackle/rpc/SubscribeStatusSpec.groovy

- reverted removing of configured upstreams in case of unavailability
- small refactoring in grpc upstreams
- fixing of bug of statuses subscription

Stabilisation of upstreams

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/DefaultUpstream.kt

it is dangerous to use `tryEmitNext` without check of result in multithreaded case. emitNext with EmitFailureHandler are safe option for such situations.
Also added logging for upstream status changes

it is dangerous to use `tryEmitNext` without check of result

---

src/main/kotlin/io/emeraldpay/dshackle/rpc/BlockchainRpc.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/DefaultUpstream.kt

Log every node status change in blockchain rpc

Change Status class to data class for better logging

---

build.gradle
gradle/libs.versions.toml
src/main/kotlin/io/emeraldpay/dshackle/rpc/BlockchainRpc.kt
src/main/kotlin/io/emeraldpay/dshackle/rpc/SubscribeNodeStatus.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/AbstractHead.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/DefaultUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/forkchoice/NoChoiceWithPriorityForkChoice.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/grpc/GrpcHead.kt

- add external subscription id
- reduce level of noisy logs

Logging tuning

---

src/main/kotlin/io/emeraldpay/dshackle/rpc/SubscribeNodeStatus.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/DefaultUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/Multistream.kt

- more event sending
- small log changes

fixes for node subscribe:

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/Multistream.kt

```
dshackle_upstreams_availability{chain="ETH",status="immature",} 0.0
dshackle_upstreams_availability{chain="ETH",status="syncing",} 0.0
dshackle_upstreams_availability{chain="ETH",status="lagging",} 0.0
dshackle_upstreams_availability{chain="ETH",status="unavailable",} 0.0
dshackle_upstreams_availability{chain="ETH",status="ok",} 2.0
dshackle_upstreams_availability_detailed{chain="ETH",status="immature",upstream="infura",} 0.0
dshackle_upstreams_availability_detailed{chain="ETH",status="immature",upstream="infura2",} 0.0
dshackle_upstreams_availability_detailed{chain="ETH",status="lagging",upstream="infura",} 0.0
dshackle_upstreams_availability_detailed{chain="ETH",status="lagging",upstream="infura2",} 0.0
dshackle_upstreams_availability_detailed{chain="ETH",status="ok",upstream="infura …
```

add detailed upstream availability metrics

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/DefaultUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/FilteredApis.kt
src/test/groovy/io/emeraldpay/dshackle/upstream/FilteredApisSpec.groovy

- now isAvailable return true in case upstreams are OK or LAGGING
- All upstreams in Filtered API now sorted by status

Adjustments in availability determination:

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/AbstractHead.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/DefaultUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/WsConnectionImpl.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/forkchoice/PriorityForkChoice.kt

- move noisy logging to trace level
- log entire broken ws message

Changes in logging

---

src/main/kotlin/io/emeraldpay/dshackle/data/BlockContainer.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/AbstractHead.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumRpcUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumUpstreamValidator.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumWsHead.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/connectors/ConnectorFactory.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/connectors/EthereumConnectorFactory.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/connectors/EthereumRpcConnector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/connectors/EthereumWsConnector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/subscribe/EthereumWsIngressSubscription.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum_pos/EthereumPosRpcUpstream.kt
src/test/groovy/io/emeraldpay/dshackle/test/ConnectorFactoryMock.groovy
src/test/groovy/io/emeraldpay/dshackle/test/EthereumPosRpcUpstreamMock.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/EthereumWsHeadSpec.groovy

- now validation of upstream starts immediately after upstream starts - it allows it became available asap
- now we don't enrich PoS blocks which improves performance and decrease number of requests to node

Upstream validation and enhancement improvement

---

src/main/kotlin/io/emeraldpay/dshackle/config/ChainsConfig.kt
src/main/kotlin/io/emeraldpay/dshackle/config/ChainsConfigReader.kt
src/main/kotlin/io/emeraldpay/dshackle/config/MainConfigReader.kt
src/main/kotlin/io/emeraldpay/dshackle/startup/ConfiguredUpstreams.kt
src/main/resources/chains.yaml
src/test/groovy/io/emeraldpay/dshackle/config/ChainsConfigReaderSpec.groovy
src/test/kotlin/io/emeraldpay/dshackle/config/ChainsConfigTest.kt

Add possibility to configure default options for chains using `chains.yaml`

Add options to chains.yaml

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/subscribe/json/NewHeadMessage.kt

Grpc Head provides limited set of information, so we need to make some new fields optional.

Fix native subscription in case grpc head subscription mode.

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/DefaultUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/Multistream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/grpc/BitcoinGrpcUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/grpc/EthereumGrpcUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/grpc/EthereumPosGrpcUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/grpc/GrpcUpstreams.kt
src/test/groovy/io/emeraldpay/dshackle/upstream/MultistreamSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/grpc/EthereumGrpcUpstreamSpec.groovy

- now provider methods updated based on availability of upstream of provider
- fixed SubscribeStatus - after new event previous subscription was canceled and new one was created instead

Update methods based on upstream availability

---

src/main/kotlin/io/emeraldpay/dshackle/quorum/NotLaggingQuorum.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/DefaultUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/Multistream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/Upstream.kt

Send to prom NaN lag value if it is null

Set default lag value to null

---

src/main/kotlin/io/emeraldpay/dshackle/BlockchainType.kt
src/main/kotlin/io/emeraldpay/dshackle/Chain.kt
src/main/kotlin/io/emeraldpay/dshackle/Global.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/calls/DefaultEthereumMethods.kt

- change hardcoded methods to map impl
- added missed bsc to hardcoded methods
- fix mumbai typo

refactoring of chains

---

src/main/kotlin/io/emeraldpay/dshackle/config/UpstreamsConfig.kt
src/main/kotlin/io/emeraldpay/dshackle/quorum/QuorumRpcReader.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/DefaultUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/calls/DefaultEthereumMethods.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumLikeRpcUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/subscribe/EthereumLabelsDetector.kt
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/EthereumLabelsDetectorSpec.groovy

Detect node client type and  whether a node is archive or not

Auto detect labels

---

docs/reference-configuration.adoc
src/main/kotlin/io/emeraldpay/dshackle/config/UpstreamsConfig.kt
src/main/kotlin/io/emeraldpay/dshackle/config/UpstreamsConfigReader.kt
src/main/kotlin/io/emeraldpay/dshackle/startup/ConfiguredUpstreams.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/HeadLagObserver.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/calls/DefaultEthereumMethods.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumLikeRpcUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumUpstreamValidator.kt
src/test/groovy/io/emeraldpay/dshackle/config/UpstreamsConfigReaderSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/HeadLagObserverSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/EthereumUpstreamValidatorSpec.groovy
src/test/kotlin/io/emeraldpay/dshackle/IntegrationTest.kt

Validate upstream chain and node chain using `chainId` and `net_version` methods. If it's not valid such upstream won't be created at all.

Add validation of chain setting

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EnrichedMergedHead.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumBlockEnricher.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumLikeMultistream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumMultistream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumWsHead.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/subscribe/ConnectBlockUpdates.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum_pos/EthereumPosMultiStream.kt
src/test/groovy/io/emeraldpay/dshackle/test/TestingCommons.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/EnrichedMergedHeadSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/subscribe/ConnectBlockUpdatesSpec.groovy

Enriched head for subscriptions to fix logs subscriptions.

Enriched merge head for ethereum subscription

---

docs/04-upstream-config.adoc
src/main/kotlin/io/emeraldpay/dshackle/BlockchainType.kt
src/main/kotlin/io/emeraldpay/dshackle/Chain.kt
src/main/kotlin/io/emeraldpay/dshackle/Global.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/calls/DefaultEthereumMethods.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumUpstreamValidator.kt
src/main/resources/chains.yaml

added retries for initial upstream validation
added fantom, gnosis and avalanche networks

new networks and retries

---

foundation/src/main/resources/chains.yaml
src/main/kotlin/io/emeraldpay/dshackle/ThrottledLogger.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/HeadLivenessValidator.kt

- set throttled logger timeout for 20 minutes
- set astar chain block time to 1m
- add throttled log to liveness checker

Liveness for Astar

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/AbstractHead.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/EmptyHead.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/Head.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/MatchesResponse.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/Selector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EnrichedMergedHead.kt
src/test/groovy/io/emeraldpay/dshackle/test/EthereumHeadMock.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/FilteredApisSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/SelectorSpec.groovy

Ability to match on slot, not only on height

slot height matcher implementation

---

foundation/src/main/resources/chains.yaml
src/main/kotlin/io/emeraldpay/dshackle/upstream/LowerBoundBlockDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/RecursiveLowerBoundBlockDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumLowerBoundBlockDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/solana/SolanaLowerBoundBlockDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/starknet/StarknetLowerBoundBlockDetector.kt
src/test/kotlin/io/emeraldpay/dshackle/upstream/RecursiveLowerBoundBlockDetectorTest.kt
src/test/kotlin/io/emeraldpay/dshackle/upstream/solana/SolanaLowerBoundBlockDetectorTest.kt

- fix the interval issue with lower calculation flux when downstream could be retried due to some reasons but upstream emits the next value
- increase lower calculation interval

Fixes lower data calculation

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/rpcclient/stream/JsonRpcStreamParser.kt
src/test/kotlin/io/emeraldpay/dshackle/upstream/rpcclient/stream/JsonRpcStreamParserTest.kt

Now we ignore all brackets inside a string value

Fix brackets calculation

---

foundation/src/main/resources/chains.yaml
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumArchiveBlockNumberReader.kt

`Zora` - L2 based on OP stack
`Mode` - L2 base on OP stack. Interesing feature - Applications and users that scale the Mode blockchain are motivated to work together and directly receive a proportion of network sequencer profits (Sequencer Fee Sharing).
`Evmos` - PoS blockchain that if fully compatible with EVM; built using CosomSDK
`Ronin` - EVM blockchain specifically forged for gaming
`Neon EVM` - Neon EVM is a fully compatible Ethereum environment solution built on the Solana blockchain. The platform allows developers to deploy Ethereum dApps without undertaking any reconfiguration.
`Boba` - L2 based on OP stack; cross-chain scaling solution, deployed on Ethereum, Avalanche, Binance chain and more.
HECO - L2
`Playnance` - gelato; based on Arbitrum Orbit - it is a new product offering …

A lot of new chains

---

foundation/src/main/resources/chains.yaml

Add Mantle Sepolia Testnet (Goerli retiring soon)

Add Mantle Sepolia

---

demo/quick-start/dshackle.yaml
docs/reference-configuration.adoc
foundation/src/main/resources/chains.yaml
foundation/src/test/kotlin/org/drpc/chainsconfig/ChainsConfigReaderTest.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/calls/DefaultEthereumMethods.kt
src/test/groovy/io/emeraldpay/dshackle/config/MainConfigReaderSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/rpc/NativeCallSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/calls/DefaultEthereumMethodsSpec.groovy
src/test/resources/configs/dshackle-full.yaml

Remove all goerli chains & astar zkatana
Also add linea sepolia, starknet sepolia and manta pacific sepolia

Remove ethereum goerli

---

.gitignore
src/main/kotlin/io/emeraldpay/dshackle/upstream/UpstreamSettingsDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/beaconchain/BeaconChainUpstreamSettingsDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumUpstreamSettingsDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/near/NearUpstreamSettingsDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/solana/SolanaUpstreamSettingsDetector.kt

Add solana, near cleint/version detecting

Node client_type & client_version not parsed for non-eth chains

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumUpstreamSettingsDetector.kt
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/EthereumUpstreamSettingsDetectorSpec.groovy

Override archive config label with real archived status

Ignore archive labels set manually

---

src/main/kotlin/io/emeraldpay/dshackle/config/context/SchedulersConfig.kt
src/main/kotlin/io/emeraldpay/dshackle/startup/ConfiguredUpstreams.kt
src/main/kotlin/io/emeraldpay/dshackle/startup/configure/GenericUpstreamCreator.kt
src/main/kotlin/io/emeraldpay/dshackle/startup/configure/UpstreamCreator.kt
src/main/kotlin/io/emeraldpay/dshackle/startup/configure/UpstreamFactory.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/DefaultUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/Selector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/bitcoin/BitcoinUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/generic/GenericMultistream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/generic/GenericUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/grpc/BitcoinGrpcUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/grpc/GenericGrpcUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/grpc/GrpcHead.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/grpc/GrpcUpstreamCreator.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/lowerbound/LowerBoundData.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/rpcclient/JsonRpcGrpcClient.kt
src/test/groovy/io/emeraldpay/dshackle/upstream/grpc/GrpcHeadSpec.groovy
src/test/kotlin/io/emeraldpay/dshackle/startup/configure/UpstreamFactoryTest.kt

Reanimate GRPC upstreams:
1. Fix creation of grpc upstreams
2. Update grpc upstream lower bounds
3. Streaming and grpc upstreams

Reanimate grpc upstreams

---

docs/reference-configuration.adoc
foundation/src/main/kotlin/io/emeraldpay/dshackle/foundation/ChainOptions.kt
foundation/src/main/kotlin/io/emeraldpay/dshackle/foundation/ChainOptionsReader.kt
foundation/src/main/kotlin/org/drpc/chainsconfig/ChainsConfig.kt
foundation/src/main/kotlin/org/drpc/chainsconfig/ChainsConfigReader.kt
foundation/src/main/resources/chains.yaml
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumUpstreamValidator.kt
src/test/groovy/io/emeraldpay/dshackle/config/UpstreamsConfigReaderSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/EthereumUpstreamValidatorSpec.groovy

On startup chack gas price for chain with specific config

Check gas price

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/UpstreamRpcMethodsDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/BasicEthUpstreamRpcMethodsDetector.kt
src/test/kotlin/io/emeraldpay/dshackle/upstream/ethereum/BasicEthUpstreamRpcMethodsDetectorTest.kt
src/test/kotlin/io/emeraldpay/dshackle/upstream/polkadot/BasicPolkadotUpstreamRpcMethodsDetectorTest.kt

fix success detection in case of error during other methods detection

detect trace_callMany
