src/main/kotlin/io/emeraldpay/dshackle/upstream/AbstractHead.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/MergedHead.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumMultistream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/connectors/EthereumRpcConnector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum_pos/EthereumPosMultiStream.kt

In AbstractHead we use `distinctUntilChanged` to not process the same blocks several times.
It works ok for MostWorkForkChoice, because it does not matter from which node head came.
However, for PriorityForkChoice it does matter. If we have one node that on average is faster that the others and we assign it the lowest priority, basically it will feed heads to ETH POS Multistream to `distinctUntilChanged` and when head comes from node with higher priority we do not even process it.
Thus, sometimes the head can stuck until node with the most priority will send its head faster.

Fix head updates in case of priority fork choice

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/WsConnection.kt

Using toJson method that correctly serializes requests that contain selectors. 
Currently it breaks WS connection.

Serialize WS JSONRpc requests correctly

---

src/main/kotlin/io/emeraldpay/dshackle/rpc/NativeCall.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/calls/AggregatedCallMethods.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/calls/CallMethods.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/calls/DefaultBitcoinMethods.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/calls/DefaultEthereumMethods.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/calls/DirectCallMethods.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/calls/EthereumCallSelector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/calls/ManagedCallMethods.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumDirectReader.kt
src/test/groovy/io/emeraldpay/dshackle/startup/ConfiguredUpstreamsSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/MultistreamSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/calls/AggregatedCallMethodsSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/calls/ManagedCallMethodsSpec.groovy

Dshackle stores values inside quorums which job is to decide the strategy of acquiring results of calling specific methods. All except ManagedCallMethods create new quorums when getQuorumFor is called. This one didn't, so if we defined some methods via config and then call a method with quorum A which succeeds, quorum writes result in its state.
If we call another successful method, no problems occur. However, if we get an error from a node, quorum writes this error in its internal state, but as its cached there is already response from previous successful call.
Thus we NEVER can cache quorums.

fix managed methods reusing old quorums

---

src/main/kotlin/io/emeraldpay/dshackle/startup/ConfiguredUpstreams.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/AbstractHead.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/Multistream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/DefaultEthereumHead.kt

**Problem:** if we have a merged head with priority from choice and head having most priority stuck - other heads hove no ability to propagate new heads and the whole multistream head stuck. 
**Fix:** if multistream becomes unavailable we remove it from the multistream and returns back once it ok 
Additionally added metrics for 
- heads have no updates over 60sec `stuck_head`
- current head height for every head `current_head`

Fix stuck heads

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/AbstractHead.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum_pos/EthereumPosMultiStream.kt

Several problems with heads were detected based on 
`2022-13-12 16:41:26.979 | WARN  |         AbstractHead | No head updates ETH Pos Multistream for 5989362 ms @ class io.emeraldpay.dshackle.upstream.MergedHead`
1. Watchdog thread was not stopped and prevent head from collected by GC 
2. MergedHead built from zero heads was not managed properly and was never stopped which leads to the problem 1

fix daemon heads + head metrics

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumUpstreamValidator.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumWsHead.kt

- we need to read full block in case totalDifficulty is null
- we need to log errors in upstream validation process

Support for wider scope of providers

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum_pos/EthereumPosRpcUpstream.kt

- now we don't enrich PoS blocks - now is default

Upstream enhancement improvement:

---

src/main/kotlin/io/emeraldpay/dshackle/startup/UpstreamChangeEvent.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/Multistream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/grpc/BitcoinGrpcUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/grpc/EthereumGrpcUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/grpc/EthereumPosGrpcUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/grpc/GrpcUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/grpc/GrpcUpstreamStatus.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/grpc/GrpcUpstreams.kt
src/test/groovy/io/emeraldpay/dshackle/upstream/grpc/GrpcUpstreamStatusSpec.groovy

Currently if upstream available methods change, we update them for that upstream.
However, we won't update Multistream available methods. Probably this is the aftereffect of not removing unavailable GRPC upstreams.
This PR changes that: introducing new UPDATED event.

new upstream change type — updated

---

src/main/kotlin/io/emeraldpay/dshackle/cache/BlocksMemCache.kt
src/main/kotlin/io/emeraldpay/dshackle/cache/Caches.kt
src/main/kotlin/io/emeraldpay/dshackle/cache/CachesFactory.kt
src/main/kotlin/io/emeraldpay/dshackle/cache/HeightByHashMemCache.kt
src/main/kotlin/io/emeraldpay/dshackle/data/BlockContainer.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/calls/EthereumCallSelector.kt
src/test/groovy/io/emeraldpay/dshackle/cache/BlockByHeightSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/cache/BlocksMemCacheSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/calls/EthereumCallSelectorSpec.groovy

- turn off cache enrichment for main - previously it was enriched but not use
- fix cache not full blocks - blocks from newHeads sub are not cached to `<BlockId, BlockContainer>` but only in hash -> height and height -> hash
- removed extra cache for requested tag
- change cache for height matcher by hash

Turn off caches for main, fix cache not enrichment blocks

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/WebsocketConnectionStatesHandler.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumWsHead.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/WsConnection.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/WsConnectionImpl.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/WsConnectionMultiPool.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/WsConnectionPool.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/WsConnectionSinglePool.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/WsSubscriptions.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/WsSubscriptionsImpl.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/subscribe/WebsocketPendingTxes.kt
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/EthereumWsHeadSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/WsConnectionMultiPoolSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/WsSubscriptionsImplSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/subscribe/WebsocketPendingTxesSpec.groovy

Add connectionInfo flux with ws states - `CONNECTED` and `DISCONNECTED`. Subscribe to it in `EthereumWsHead` and as soon as `CONNECTED` event is come try to restart and resubscribe to newHeads.

Resubscribe to newHeads immediately after reconnection

---

src/main/kotlin/io/emeraldpay/dshackle/Defaults.kt
src/main/kotlin/io/emeraldpay/dshackle/GrpcServer.kt
src/main/kotlin/io/emeraldpay/dshackle/config/spans/ClientSpansInterceptor.kt
src/main/kotlin/io/emeraldpay/dshackle/config/spans/ErrorSpanHandler.kt
src/main/kotlin/io/emeraldpay/dshackle/config/spans/ServerSpansInterceptor.kt
src/main/kotlin/io/emeraldpay/dshackle/config/spans/SpanConfig.kt
src/main/kotlin/io/emeraldpay/dshackle/startup/ConfiguredUpstreams.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/grpc/GrpcUpstreams.kt
src/main/resources/application.yml
src/test/groovy/io/emeraldpay/dshackle/startup/ConfiguredUpstreamsSpec.groovy
src/test/kotlin/io/emeraldpay/dshackle/config/spans/CollectSpanConfigTest.kt
src/test/kotlin/io/emeraldpay/dshackle/config/spans/ErrorSpanHandlerTest.kt

Add client and server interceptors to send error spans via header to main dshackle with subsequent sending to tempo. Also this feature could be turned off via env variable.
To collect spans on provider side `Caffeine` cache is used just to be sure that extra spans will be removed.

Collect error spans from providers

---

src/main/java/io/emeraldpay/dshackle/upstream/ethereum/json/TransactionJsonSnapshot.java
src/main/java/io/emeraldpay/dshackle/upstream/ethereum/json/TransactionJsonSnapshotDeserializer.java
src/main/kotlin/io/emeraldpay/dshackle/data/TxContainer.kt
src/main/kotlin/io/emeraldpay/dshackle/rpc/TrackEthereumTx.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumCachingReader.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumDirectReader.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumFees.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumLegacyFees.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumPriorityFees.kt
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/EthereumLegacyFeesSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/EthereumPriorityFeesSpec.groovy

There was a performance  problem with getting tx by hash - tx can have a large `input` field which and it was a bottleneck during deserialization. Now we deserialize only necessary data like hash, height and blockHash.

Better performance of tx deserialization

---

src/main/kotlin/io/emeraldpay/dshackle/config/ChainsConfig.kt
src/main/kotlin/io/emeraldpay/dshackle/config/ChainsConfigReader.kt
src/main/kotlin/io/emeraldpay/dshackle/config/UpstreamsConfig.kt
src/main/kotlin/io/emeraldpay/dshackle/config/UpstreamsConfigReader.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumLikeRpcUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumLikeUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumUpstreamValidator.kt
src/main/resources/chains.yaml
src/test/groovy/io/emeraldpay/dshackle/config/ChainsConfigReaderSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/config/UpstreamsConfigReaderSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/test/EthereumPosRpcUpstreamMock.groovy
src/test/groovy/io/emeraldpay/dshackle/test/TestingCommons.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/EthereumUpstreamValidatorSpec.groovy
src/test/resources/configs/chains-basic.yaml
src/test/resources/configs/upstreams-validation.yaml

Added new kind of validation, that check return limit for a node. Default return limit is 100k, we need at least 200k.
Infura, Alchemy do not have limit, they just rely on gas limit to limit the return. So, we may increase this limit in future, however it opens potential exploits.
Now limit is tested for 2 networks: Goerli and Ethereum Mainnet, because we use custom smart contract to generate huge responses, contract code is: `
```solidity
pragma solidity ^0.8.12;
contract testContract {
constructor () {
}
function get (uint32 size) view public returns(bytes32[] memory) {
uint iter = size / 32 + 1;
bytes32 pattern = blockhash(block.number - 1);
bytes32[] memory accum = new bytes32[](iter);
for (uint32 i = 0; i < iter; i++) 
{
accum[i] = pattern;
}
return accum;
}
}
```

Checking eth_call return limit during node validation, currently 200k

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumLikeRpcUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/subscribe/EthereumLabelsDetector.kt
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/EthereumLabelsDetectorSpec.groovy

There is an interesting behaviour for those networks where nodes has redirects to previous versions of nodes (say pre-bedrock).
So in case of Optimism pre-bedrock node can be archive so it has state for 0x1 block, however after bedrock can be non-archive so say currentBlock - 10k state is not available.

Improve archive detection algorithm for node

---

src/main/kotlin/io/emeraldpay/dshackle/quorum/AlwaysQuorum.kt
src/main/kotlin/io/emeraldpay/dshackle/quorum/BroadcastQuorum.kt
src/main/kotlin/io/emeraldpay/dshackle/quorum/CallQuorum.kt
src/main/kotlin/io/emeraldpay/dshackle/quorum/NotLaggingQuorum.kt
src/main/kotlin/io/emeraldpay/dshackle/quorum/NotNullQuorum.kt
src/main/kotlin/io/emeraldpay/dshackle/quorum/QuorumRpcReader.kt
src/main/kotlin/io/emeraldpay/dshackle/quorum/ValueAwareQuorum.kt
src/main/kotlin/io/emeraldpay/dshackle/rpc/NativeCall.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/WsConnectionImpl.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/rpcclient/JsonRpcError.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/rpcclient/JsonRpcException.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/rpcclient/JsonRpcHttpClient.kt
src/test/groovy/io/emeraldpay/dshackle/proxy/WriteRpcJsonSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/quorum/AlwaysQuorumSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/quorum/BroadcastQuorumSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/quorum/NotLaggingQuorumSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/quorum/NotNullQuorumSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/quorum/ValueAwareQuorumSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/rpc/NativeCallSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/EthereumCachingReaderSpec.groovy

- return `upstreamId` in native call response for errors not only for positive cases
- remove response upstreamId from span in dshackle, it should be moved to dproxy side
- refactoring of `CallQuorum` classes, there were an overhead using upstreams and `providedUpstreamId`

Return upstreamId in response for errors too

---

src/main/kotlin/io/emeraldpay/dshackle/rpc/NativeCall.kt
src/main/kotlin/io/emeraldpay/dshackle/rpc/TrackEthereumAddress.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumCachingReader.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumDirectReader.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumLocalReader.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/subscribe/ProduceLogs.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/rpcclient/JsonRpcResponse.kt
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/EthereumCachingReaderSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/EthereumLocalReaderSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/subscribe/ProduceLogsSpec.groovy

Before that we received a multistream id as a response upstream id in the case of `LocalReader`. It's not always true. We can also get an upstreamId when we send a request direct through `DirectReader`. So we fix it.

Return upstreamId from direct reader

---

src/main/kotlin/io/emeraldpay/dshackle/quorum/AlwaysQuorum.kt
src/main/kotlin/io/emeraldpay/dshackle/quorum/BroadcastQuorum.kt
src/main/kotlin/io/emeraldpay/dshackle/quorum/CallQuorum.kt
src/main/kotlin/io/emeraldpay/dshackle/quorum/MaximumValueQuorum.kt
src/main/kotlin/io/emeraldpay/dshackle/quorum/NotLaggingQuorum.kt
src/main/kotlin/io/emeraldpay/dshackle/quorum/NotNullQuorum.kt
src/main/kotlin/io/emeraldpay/dshackle/reader/BroadcastReader.kt
src/main/kotlin/io/emeraldpay/dshackle/reader/RpcReaderFactory.kt
src/main/kotlin/io/emeraldpay/dshackle/rpc/NativeCall.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/calls/DefaultEthereumMethods.kt
src/test/groovy/io/emeraldpay/dshackle/quorum/BroadcastQuorumSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/quorum/MaximumValueQuorumSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/quorum/ValueAwareQuorumSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/reader/BroadcastReaderSpec.groovy

Fixes problem when we ask amount of transactions for user including mempool. Unfortunately, it's not always possible to propagate transaction to all nodes, so we need to ask all nodes and select maximum.

Maximum value quorum for BroadcastReader

---

src/main/kotlin/io/emeraldpay/dshackle/HeapDumpCreator.kt
src/main/kotlin/io/emeraldpay/dshackle/Starter.kt

Add settings for heap dump creation programmatically in order to create not only the first heap dump. Max dump count is 3, then the earliest dump is deleted. Also every 30 minutes it prints the warn message if there are some heap dumps.

Settings for heap dumps creation

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumArchiveBlockNumberReader.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumLikeRpcUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/subscribe/EthereumLabelsDetector.kt
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/EthereumLabelsDetectorSpec.groovy

Now we add for detection archive label a new check for the earliest block. There are also corner cases for arbitrum and optimism, for them we check nitro and bedrock block.

Fix archive detection

---

src/main/kotlin/io/emeraldpay/dshackle/rpc/Describe.kt
src/main/kotlin/io/emeraldpay/dshackle/rpc/StreamHead.kt
src/main/kotlin/io/emeraldpay/dshackle/startup/configure/GenericUpstreamCreator.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/LowerBoundBlockDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/Multistream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/RecursiveLowerBoundBlockDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/Upstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/bitcoin/BitcoinRpcUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumChainSpecific.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumLowerBoundBlockDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/generic/ChainSpecific.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/generic/GenericUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/grpc/BitcoinGrpcUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/grpc/GenericGrpcUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/polkadot/PolkadotChainSpecific.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/polkadot/PolkadotLowerBoundBlockDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/solana/SolanaChainSpecific.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/solana/SolanaLowerBoundBlockDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/starknet/StarknetChainSpecific.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/starknet/StarknetLowerBoundBlockDetector.kt
src/test/groovy/io/emeraldpay/dshackle/test/GenericUpstreamMock.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/FilteredApisSpec.groovy
src/test/kotlin/io/emeraldpay/dshackle/upstream/RecursiveLowerBoundBlockDetectorTest.kt
src/test/kotlin/io/emeraldpay/dshackle/upstream/solana/SolanaLowerBoundBlockDetectorTest.kt
src/test/kotlin/io/emeraldpay/dshackle/upstream/starknet/StarknetLowerBoundBlockDetectorTest.kt

Now we can determine the lower block:
- for eth chains and polkadot we use the recursive algorithm with binary search to determine the lower block
- for starknet we assume that all nodes are archive
- for solana we use its method `getFirstAvailableBlock` to get the first available slot and then using it get the lower block height
We try to update this value each minute and then calculate it in multistream by chain. Also we update it according to the availability of upstreams.
There is a default value for the slot and the block height - 0 and 0. And if so it means we haven't performed the job for the determination yet.

Add determination of the lower block

---

docs/04-upstream-config.adoc
foundation/src/main/resources/chains.yaml

Zksync Goerli is EOL in Jan 24 as per their [announcment](https://github.com/zkSync-Community-Hub/zksync-developers/discussions/228)
This PR adds zksync-sepolia support to chains.yaml

adds zksync-sepolia support

---

src/main/kotlin/io/emeraldpay/dshackle/startup/ConfiguredUpstreams.kt
src/main/kotlin/io/emeraldpay/dshackle/startup/UpstreamChangeEvent.kt
src/main/kotlin/io/emeraldpay/dshackle/startup/configure/BitcoinUpstreamCreator.kt
src/main/kotlin/io/emeraldpay/dshackle/startup/configure/EthereumUpstreamCreator.kt
src/main/kotlin/io/emeraldpay/dshackle/startup/configure/GenericUpstreamCreator.kt
src/main/kotlin/io/emeraldpay/dshackle/startup/configure/UpstreamCreator.kt
src/main/kotlin/io/emeraldpay/dshackle/startup/configure/UpstreamFactory.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/Multistream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/generic/GenericUpstream.kt

Now we make the upstream settings validation periodically. We want to remove and add upstreams according to the result of this validation. Because of that we must change a bit the current logic:
- We've added two more upstream event types: `FATAL_SETTINGS_ERROR_REMOVED` and `OBSERVED`. We use `FATAL_SETTINGS_ERROR_REMOVED` event type to remove an invalid upstream but not stop it and `OBSERVED`  to add an upstream to the observation of its states.
- On startup we perform the settings validation: 1) if we get an fatal error we don't create such upstream, 2) if we get a non fatal error we add this upstream to the observation, create it but not start until we get a valid status of the validation 3) if we get a valid result we just start an upstream.
- After an upstream has started we perform …

Make settings validation periodically

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/LowerBoundBlockDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/solana/SolanaLowerBoundBlockDetector.kt
src/test/kotlin/io/emeraldpay/dshackle/upstream/RecursiveLowerBoundBlockDetectorTest.kt
src/test/kotlin/io/emeraldpay/dshackle/upstream/solana/SolanaLowerBoundBlockDetectorTest.kt

- there is no need to use `getBlocks` method in lower bound detection since `getFirstAvailableBlock` returns the slot of the lowest confirmed block
- add `switchIfEmpty` operator to prevent getting stuck in lower bound detection
- there is no need to retry solana errors infinitely

Improve solana lower bound detection

---

src/main/kotlin/io/emeraldpay/dshackle/rpc/NativeCall.kt
src/test/kotlin/io/emeraldpay/dshackle/rpc/NativeCallTest.kt

We do it only once - on the very first chunk. There is no need to transfer this field on all chunks.

Write response upstreamId in streaming

---

src/main/kotlin/io/emeraldpay/dshackle/rpc/NativeCall.kt

Because if this `sort` we can have an issue when all requests get stuck due to there are no any more connections and `Flux.sort` waits for all elements and only then carries out sorting. In this case we get a specific deadlock - remain requests are added to the queue and they wait for a connection, but `sort` at the same time wants all elements.
So we can freely remove it because we already have a sorting algorithm on our dproxy side.

Remove NativeCall sort

---

src/main/kotlin/io/emeraldpay/dshackle/proxy/WebsocketHandler.kt

Jackson serializes byte array in the base64 format, that's why our proxy `newHeads` sub worked incorrectly.

Fix proxy newHeads sub

---

foundation/src/main/resources/chains.yaml

Adds [Polygon zkevm cardona testnet](https://chainlist.org/chain/2442), which will succeed the existing Zkevm mango testnet (goerli)

adds polygon zkevm cardona testnet

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/DefaultNearMethods.kt

Add send_tx method https://docs.near.org/api/rpc/transactions 
Remove broadcast_tx_* deprecated methods https://docs.near.org/api/rpc/transactions#send-transaction-async
Remove view_access_key method (it's not a method, it's a query method option) https://docs.near.org/api/rpc/access-keys#view-access-key

Update NEAR methods list

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/UpstreamSettingsDetector.kt

Track client nodes versions also in case of bad parsing
Example:
filecoin i eth-like chain, but for example https://node.filutils.com/rpc/v1 node for request "web3_clientVersion" return "1.26.2+mainnet+git.464a1e856.dirty" version, but we expected "Geth/v10.0.0/drpc"

Track client nodes versions

---

src/main/kotlin/io/emeraldpay/dshackle/config/context/SchedulersConfig.kt
src/main/kotlin/io/emeraldpay/dshackle/quorum/QuorumRequestReader.kt
src/main/kotlin/io/emeraldpay/dshackle/reader/BroadcastReader.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/DefaultUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/Multistream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/Upstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/beaconchain/BeaconChainLowerBoundStateDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/error/EthereumStateLowerBoundErrorHandler.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/error/UpstreamErrorHandler.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumLowerBoundBlockDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumLowerBoundStateDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/generic/GenericUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/lowerbound/LowerBoundDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/lowerbound/LowerBoundService.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/lowerbound/detector/RecursiveLowerBound.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/near/NearLowerBoundStateDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/polkadot/PolkadotLowerBoundStateDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/solana/SolanaLowerBoundSlotDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/starknet/StarknetLowerBoundStateDetector.kt
src/test/kotlin/io/emeraldpay/dshackle/upstream/error/EthereumStateLowerBoundErrorHandlerTest.kt
src/test/kotlin/io/emeraldpay/dshackle/upstream/error/UpstreamErrorHandlerTest.kt

We must calculate the next lower bound only inside the range `lowerBound-head`. Also we have to track errors from nodes and update lower bounds if we face with some error types.

Calculate lower bounds inside range + adaptive update

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumLowerBoundService.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumLowerBoundTxDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/lowerbound/detector/RecursiveLowerBound.kt
src/test/kotlin/io/emeraldpay/dshackle/upstream/RecursiveLowerBoundServiceTest.kt

We try to find the tx lower bound. But it is much trickier then other bounds due to not each block can have txs and it's ok. So we need to shift a bit and check other blocks. And yet we can't detect precisely the very first block with tx without a lot of requests. Probably it's ok though.

Tx lower bound

---

src/main/kotlin/io/emeraldpay/dshackle/Global.kt
src/main/kotlin/io/emeraldpay/dshackle/config/MainConfig.kt
src/main/kotlin/io/emeraldpay/dshackle/config/UpstreamsConfig.kt
src/main/kotlin/io/emeraldpay/dshackle/config/reload/ReloadConfigService.kt
src/main/kotlin/io/emeraldpay/dshackle/config/reload/ReloadConfigSetup.kt
src/test/kotlin/io/emeraldpay/dshackle/config/reload/ReloadConfigTest.kt

Since we can change the current upstream config we need to keep the initial one that is not modified and compare it with a new config.

Fix config reload

---

src/main/kotlin/io/emeraldpay/dshackle/rpc/BlockchainRpc.kt
src/main/kotlin/io/emeraldpay/dshackle/rpc/ChainEventMapper.kt
src/main/kotlin/io/emeraldpay/dshackle/rpc/NativeCall.kt
src/main/kotlin/io/emeraldpay/dshackle/rpc/SubscribeChainStatus.kt
src/main/kotlin/io/emeraldpay/dshackle/startup/QuorumForLabels.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/AbstractHead.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/DefaultUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/EmptyHead.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/Head.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/Multistream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/calls/DisabledCallMethods.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumFinalizationDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/generic/GenericUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/state/MultistreamState.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/state/MultistreamStateEvent.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/state/MultistreamStateHandler.kt
src/test/groovy/io/emeraldpay/dshackle/test/EthereumHeadMock.groovy
src/test/kotlin/io/emeraldpay/dshackle/rpc/SubscribeChainStatusTest.kt
src/test/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumFinalizationDetectorTest.kt
src/test/kotlin/io/emeraldpay/dshackle/upstream/state/MultistreamStateHandlerTest.kt
src/test/kotlin/io/emeraldpay/dshackle/upstream/state/MultistreamStateTest.kt

We want to bring in one reactive endpoint with events across all chains so that there is no longer need to use `Describe` and `SubscribeHead` methods.
What have done:
- one generic reactive endpoint `SubscribeChainStatus`
- small `Multistream` refactoring - new MultistreamState has been created to handle its state

New reactive endpoint

---

src/main/kotlin/io/emeraldpay/dshackle/proxy/BaseHandler.kt
src/main/kotlin/io/emeraldpay/dshackle/proxy/WebsocketHandler.kt
src/main/kotlin/io/emeraldpay/dshackle/quorum/QuorumRequestReader.kt
src/main/kotlin/io/emeraldpay/dshackle/reader/BroadcastReader.kt
src/main/kotlin/io/emeraldpay/dshackle/reader/RequestReaderFactory.kt
src/main/kotlin/io/emeraldpay/dshackle/rpc/NativeCall.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ChainCallError.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ChainCallUpstreamException.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ChainException.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ChainResponse.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumCachingReader.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumDirectReader.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumLocalReader.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/WsConnectionImpl.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/rpcclient/JsonRpcGrpcClient.kt
src/test/groovy/io/emeraldpay/dshackle/proxy/BaseHandlerSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/proxy/HttpHandlerSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/proxy/WebsocketHandlerSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/proxy/WriteRpcJsonSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/reader/BroadcastReaderSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/rpc/NativeCallSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/test/ApiReaderMock.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/EthereumCachingReaderSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/EthereumLocalReaderSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/subscribe/ProduceLogsSpec.groovy
src/test/groovy/io/emeraldpay/dshackle/upstream/rpcclient/JsonRpcResponseSpec.groovy
src/test/kotlin/io/emeraldpay/dshackle/rpc/NativeCallTest.kt

To understand clearly what upstreams handled transactions now we pass all of them in the grpc responses

Pass all upstreams that resolved a request

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumLowerBoundTxDetector.kt
src/test/kotlin/io/emeraldpay/dshackle/upstream/RecursiveLowerBoundServiceTest.kt

Unfortunately `eth_getBlockTransactionCountByNumber ` logic doesn't work, because this method can show that there are txs but actually they don't exist.
Current logic utilize a `eth_getBlockByNumber` method, checks if there are txs in a block and if so, checks if the very first tx exists.

Rework tx lower bound logic

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumUpstreamSettingsDetector.kt
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/EthereumUpstreamSettingsDetectorSpec.groovy

- using gasleft to detect amount of gas nodes provides
- we use state override to not deploy contracts everywhere, some clients (like besu and nethermind) do not support it, but most of the clients do

detect gas limit for a node

---

buildSrc/src/main/kotlin/chainsconfig.codegen.gradle.kts
gradle/libs.versions.toml
src/main/kotlin/io/emeraldpay/dshackle/upstream/DefaultUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/MatchesResponse.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/Multistream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/Selector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/Upstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/beaconchain/BeaconChainLowerBoundService.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/beaconchain/BeaconChainLowerBoundStateDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/cosmos/CosmosLowerBoundService.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumLowerBoundBlockDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumLowerBoundLogsDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumLowerBoundStateDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumLowerBoundTxDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/generic/GenericUpstream.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/lowerbound/LowerBoundDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/lowerbound/LowerBoundService.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/lowerbound/LowerBounds.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/lowerbound/detector/RecursiveLowerBound.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/near/NearLowerBoundStateDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/polkadot/PolkadotLowerBoundStateDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/solana/SolanaLowerBoundSlotDetector.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/starknet/StarknetLowerBoundService.kt
src/main/kotlin/io/emeraldpay/dshackle/upstream/starknet/StarknetLowerBoundStateDetector.kt
src/test/kotlin/io/emeraldpay/dshackle/upstream/SelectorTest.kt
src/test/kotlin/io/emeraldpay/dshackle/upstream/lowerbound/LowerBoundServiceTest.kt
src/test/kotlin/io/emeraldpay/dshackle/upstream/lowerbound/LowerBoundsPredictionTest.kt
src/test/kotlin/io/emeraldpay/dshackle/upstream/lowerbound/RecursiveLowerBoundServiceTest.kt
src/test/kotlin/io/emeraldpay/dshackle/upstream/solana/SolanaLowerBoundServiceTest.kt
src/test/kotlin/io/emeraldpay/dshackle/upstream/starknet/StarknetLowerBoundStateDetectorTest.kt

- now we also predict lower bound on the dshackle side
- because of that we can use `LowerHeightMatcher` with a specific height to filter upstreams and spread load
- for some specific cases we preserve using a sort instead `LowerHeightMatcher`

Predict lower height and use lower height matcher

---

src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/EthereumEgressSubscription.kt
src/test/groovy/io/emeraldpay/dshackle/upstream/ethereum/EthereumEgressSubscriptionSpec.groovy

In filter params you cat use topic type as
[]string
or
[][]string
For example 
```
{
"jsonrpc": "2.0",
"method": "eth_subscribe",
"params": [
"logs",
{
"address": [
"0xFc00000000000000000000000000000000000001",
],
"topics": [
["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"]
]
}
],
"id": 1
}
```
OR
```
{
"jsonrpc": "2.0",
"method": "eth_subscribe",
"params": [
"logs",
{
"address": [
"0xFc00000000000000000000000000000000000001",
],
"topics": [
"0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"
]
}
],
"id": 1
}
```

eth_subscribe: fix preparing filter
